apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-ingress
  labels:
    name: k8s-ingress
spec:
  rules:
    - host: achyuthvarma.com
      http:
        paths:
          - path: "/"
            backend:
              service:
                serviceName: next-client-service
                servicePort: 3000
