apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: k8s-ingress-nginx
  labels:
    name: k8s-ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: achyuthvarma.com
      http:
        paths:
          - path: "/"
            backend:
              service:
                serviceName: next-client-service
                servicePort: 3000
