apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    email: achyuth.varma1@gmail.com

    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the Http-01 challange provider
    solvers:
      - http01:
          ingress:
            class: nginx
