apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory

    email: achyuth.varma1@outlook.com

    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the Http-01 challange provider
    solvers:
      - http01:
          ingress:
            class: nginx
